version: "3"
services:
  prometheus-opentelemetry-example-app:
    image: openjdk:11-jre
    network_mode: host
    ports:
      - "5005:5005"
    volumes:
      - ./target/example-exporter-opentelemetry.jar:/example-exporter-opentelemetry.jar
    command:
      - java
      - -jar
      #- -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
      - /example-exporter-opentelemetry.jar
  collector:
    image: otel/opentelemetry-collector-contrib:0.79.0
    network_mode: host
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/otelcol-config.yaml:/config.yaml
    command:
      - --config=file:/config.yaml
  prometheus:
    image: prom/prometheus:v2.45.0
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/prometheus.yaml
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --config.file=/prometheus.yaml
